version: '3'

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./
    image: nextjs
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - app-next

  webserver:
    depends_on:
      - nextjs
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-next

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email nozami.id@gmail.com --agree-tos --no-eff-email --staging -d nozami.id -d www.nozami.id

volumes:
  certbot-etc:

networks:
  app-next:
    driver: bridge